### ISSUE TITLE
测速发现ping不通怎么办？

### ISSUE THREAD

**Issue by shunichio** [elecV2/blog#1]
请大佬指点。

**Comment by shunichio** [comment]
尝试更换 deployment-name 也不行

**Comment by elecV2** [comment]
> 请大佬指点。

尝试浏览器打开 你的的域名+/elecV2（类似 https://xxxxx-xxxx.cloud.okteto.net/elecV2 ），如果结果是Bad request，说明服务器安装没有问题，检测一下客户端参数填写对了没。
各个软件PING的原理不一样，不用太在意这个。

**Comment by shunichio** [comment]
显示的是：找不到xxxx-xxxxxx.cloud.okteto.net的网页。。加上/elecV2这个路径才显示的：Bad Request。客户端使用的qx，就是按照您提供的文档那样填的。

**Comment by shunichio** [comment]
> > 请大佬指点。
> 
> 尝试浏览器打开 你的的域名+/elecV2（类似 https://xxxxx-xxxx.cloud.okteto.net/elecV2 ），如果结果是Bad request，说明服务器安装没有问题，检测一下客户端参数填写对了没。
> 各个软件PING的原理不一样，不用太在意这个。

延迟测试成功了，谢谢大佬。

**Comment by insoxin** [comment]
我貌似也遇到这个情了
```
v2-6c99-d9nk4v2V2Ray 4.20.0 (V2Fly, a community-driven edition of V2Ray.) Custom
v2-6c99-d9nk4v2A unified platform for anti-censorship.
v2-6c99-d9nk4v22020/04/05 10:19:27 [Warning] v2ray.com/core: V2Ray 4.20.0 started
v2-6c99-d9nk4v22020/04/05 10:22:41 *:59474 rejected v2ray.com/core/proxy/vmess/encoding: invalid user

```
/elecV2

是Bad Request

**Comment by elecV2** [comment]
> 我貌似也遇到这个情了
> 
> ```
> v2-6c99-d9nk4v2V2Ray 4.20.0 (V2Fly, a community-driven edition of V2Ray.) Custom
> v2-6c99-d9nk4v2A unified platform for anti-censorship.
> v2-6c99-d9nk4v22020/04/05 10:19:27 [Warning] v2ray.com/core: V2Ray 4.20.0 started
> v2-6c99-d9nk4v22020/04/05 10:22:41 *:59474 rejected v2ray.com/core/proxy/vmess/encoding: invalid user
> ```
> 
> /elecV2
> 
> 是Bad Request

看前面的回答。这表示服务器是成功的，挨个检查一下客户端的参数（域名、path、uuid这些）
