### ISSUE TITLE
已经找不到选项了

### ISSUE THREAD

**Issue by wuwangxu** [elecV2/blog#2]
已经找不到选项了

**Comment by elecV2** [comment]
去看了一下，好像deploy那里的container还真的是用不了了。估计是被薅羊毛薅多了🙈。去了解一下k8s和docker吧，用kubectl命令行配合文章中的docker应该还能搭出来。具体步骤就不写了，薅羊毛的多了，对人家平台不好，对我也不好🐶（又少了一个免费的服务器

**Comment by hmsjy2017** [comment]
WordPress 也没了

**Comment by hmsjy2017** [comment]
container又回来了
![1C9E531D-FED8-48A5-9756-F778CDFA0F0E](https://user-images.githubusercontent.com/42692274/78903931-68d66280-7aae-11ea-8adc-b2a983dcb5a2.png)
