### ISSUE TITLE
请求帮助！

### ISSUE THREAD

**Issue by shunichio** [elecV2/blog#4]
我在大佬的电报频道看到大佬提供了一个QuanXJS下载的捷径。我在想大佬能否帮忙精简一下这个指令呢？目前需求是这样的，用户可以简单编辑这个快捷指令，自己在某一个操作项填入多个JS的直链，而不是执行快捷指令的时候弹窗让用户输入单个直链。编辑完成以后，执行快捷指令，根据指令里面的JS链接，直接就下载好所有的JS文件，无需任何弹窗确认。不要弹窗确认的目的是为了使用捷径的自动化功能每天定时运行这个捷径，自动下载JS文件。

我在电报频道联系不到大佬，故此只能在这儿开issue。希望没有打扰到大佬。

**Comment by elecV2** [comment]
这个可以有，有时间整一个。

**Comment by elecV2** [comment]
> 我在大佬的电报频道看到大佬提供了一个QuanXJS下载的捷径。我在想大佬能否帮忙精简一下这个指令呢？目前需求是这样的，用户可以简单编辑这个快捷指令，自己在某一个操作项填入多个JS的直链，而不是执行快捷指令的时候弹窗让用户输入单个直链。编辑完成以后，执行快捷指令，根据指令里面的JS链接，直接就下载好所有的JS文件，无需任何弹窗确认。不要弹窗确认的目的是为了使用捷径的自动化功能每天定时运行这个捷径，自动下载JS文件。
> 
> 我在电报频道联系不到大佬，故此只能在这儿开issue。希望没有打扰到大佬。

已发布 https://t.me/elecV2/52
